// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKrOVB-VtVWHoIr7kyen7PETHgg2tFSE0',
    appId: '1:678683577771:web:8ffd54e4b82d5de5bbd6ee',
    messagingSenderId: '678683577771',
    projectId: 'gpsi-4d8c0',
    authDomain: 'gpsi-4d8c0.firebaseapp.com',
    storageBucket: 'gpsi-4d8c0.appspot.com',
    measurementId: 'G-1Z57MW5KEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWmoyowIebzSUYCG0A-MK9MP9-1qDOZQ',
    appId: '1:678683577771:android:475edbe383027624bbd6ee',
    messagingSenderId: '678683577771',
    projectId: 'gpsi-4d8c0',
    storageBucket: 'gpsi-4d8c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeQSBaUtyG4NxL8czxUgywC_6-4uMkG9I',
    appId: '1:678683577771:ios:0ab7b5e0854a0896bbd6ee',
    messagingSenderId: '678683577771',
    projectId: 'gpsi-4d8c0',
    storageBucket: 'gpsi-4d8c0.appspot.com',
    iosBundleId: 'com.example.gpsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeQSBaUtyG4NxL8czxUgywC_6-4uMkG9I',
    appId: '1:678683577771:ios:0ab7b5e0854a0896bbd6ee',
    messagingSenderId: '678683577771',
    projectId: 'gpsi-4d8c0',
    storageBucket: 'gpsi-4d8c0.appspot.com',
    iosBundleId: 'com.example.gpsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKrOVB-VtVWHoIr7kyen7PETHgg2tFSE0',
    appId: '1:678683577771:web:b72f81b31c5f1c88bbd6ee',
    messagingSenderId: '678683577771',
    projectId: 'gpsi-4d8c0',
    authDomain: 'gpsi-4d8c0.firebaseapp.com',
    storageBucket: 'gpsi-4d8c0.appspot.com',
    measurementId: 'G-HFMRFH4ZDS',
  );

}